### ISSUE TITLE
k8s: Deploy TiddlyWIki on Linode LKE

### ISSUE THREAD

**Issue by mrzzy** [mrzzy/nimbus#20]
### Motivation
Deploy TiddlyWiki to host personal notetaking.

### Requirements
Deploy [TiddyWiki on NodeJS](https://tiddlywiki.com/#GettingStarted%20-%20Node.js):
- [with plugins](https://tiddlywiki.com/static/Installing%2520a%2520plugin%2520from%2520the%2520plugin%2520library.html)
  - code mirror plugin
  - markdown plugin
  - formula plugin
  - katex plugin
  - relink plugin
  - tw5-extendedit plugin
  - edit-autolist
  - notebook theme
  - TWCrosslinks
  - Context Plugin
- Secure TiddlyWiki with OAuth Authentication
- Make TiddlyWiki accessible from anywhere over TLS
- Automated backups to archive TiddyWiki to Wasabi cloud storage.

#### Architecture
![Tiddlywiki Deployment Architecture](https://user-images.githubusercontent.com/15938899/129316713-e1d0dbc9-7882-4f3d-aa2d-d7ad3c7ec536.jpg)

#### OAuth Authentication
Authentication flow:
- user makes request to oauth2-proxy.
- oauth2-proxy performs OAuth authorization grant with Keycloak.
- user is redirected to Keycloak sign in to sign in.
- oauth2-proxy sets session cookie.
- oauth2-proxy starts proxying  requests to Tiddywiki.

#### Backup Workflow
Backup flow:
- Tiddlywiki handles user requests and writes tiddlers to disk.
- [Sftp server](https://github.com/atmoz/sftp) exposes tiddlers via SFTP.
- Backup pipeline (Argo Workflow) downloads tiddlers & uploads them to Wasabi S3.
    - Use `rclone` to copy tiddler files from sftp to Wasabi S3.

#### Todo
- [x] Compile [TiddyWiki docker image with TiddyWiki &amp; Plugins](https://github.com/mrzzy/tiddywiki-docker) properly configured
- [x] Write k8s manifests (ie Deployment) for deploying TiddyWiki on Linode K8s.
- [x] Deploy keycloak as OAuth2 provider via keycloak-operator
- [x] Deploy [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) sidecar to add OAuth2 auth to TiddlyWiki
- [x] Create `wiki.mrzzy.co` DNS CNAME and point it at Ingress IP
- [x] Expose TiddlyWiki via Ingress with LetsEncrypt TLS.
- [x] Deploy Argo Workflow Engine
- [ ] Expose Tiddler files on written by TIddlywiki instance via SFTP.
- [ ] Write Argo Workflow to backup TiddlyWiki Wasabi S3

**Comment by mrzzy** [comment]
#### Design Decision: SFTP over NFS
Switched from NFS to SFTP to export Tiddler files as:
- NFS is alot more complicated to configure than SFTP.
- NFS is meant to support live filesystem mounts, we only need a snapshot of the tiddlers at a point in time.
